/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 845c0e87f60710b59ba200d8a61fe9c8)
interface __BaseEnv_Env {
	AI: Ai;
	CelmuxCallAgent: DurableObjectNamespace<import("./src/index").CelmuxCallAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CelmuxCallAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
